version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: fire-stone-hosting-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fire-stone-hosting-db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
