version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: fire-stone-hosting-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fire-stone-hosting-db
    ports:
      - 5432:5432

    # Uncomment the following block to have persistent data
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
# volumes:
#   pgdata:
